DEF_ERR(OK, "No error")
DEF_ERR(MEMORY_ALLOCATION_FAILURE, "Failed to allocate memory")
DEF_ERR(NULL_LIST_PASSED, "Null list passed to the function")
DEF_ERR(NULL_NEXT_ARRAY_PASSED, "Null next[] array passed to the function")
DEF_ERR(NULL_PREV_ARRAY_PASSED, "Null prev[] array passed to the function")
DEF_ERR(NULL_FILE_PASSED,       "Null FILE* file passed to the function")
DEF_ERR(NULL_DATA_ARRAY_PASSED, "Null data[] array passed to the function")
DEF_ERR(INVALID_HEAD_INDEX, "Invalid head index")
DEF_ERR(INVALID_TAIL_INDEX, "Invalid tail index")
DEF_ERR(INVALID_FREE_INDEX, "Invalid free index")
DEF_ERR(INVALID_INDEX_PASSED, "Invalid index passed to the function")
DEF_ERR(ELEMENT_DOESNT_EXIST, "Given element doesn't exist")